### ISSUE TITLE
produce report from workshop

### ISSUE THREAD

**Issue by reynaj** [underwatervideo/UnderwaterVideoWorkingGroup#1]
Details TBD

**Comment by hohonuuli** [comment]
:clap:

**Comment by vlferrini** [comment]
deadline: last week

**Comment by VictorZykov** [comment]
For reference, here's the Workshop web page
http://www.marine-geo.org/community/video_workshop.php
with [embedded agenda](https://docs.google.com/document/d/1pl5LwWTNMahL0Wohm8-w8HtXWW3Q3Z-0_TSfTRktmCU/edit) that includes presentation slides and workshop notes

**Comment by vlferrini** [comment]
Done! 
https://github.com/underwatervideo/UnderwaterVideoWorkingGroup/blob/master/Meetings/2016_Workshop/Documents/FINAL-2016VideoWorkshopReport.pdf
